services:
  Claroline\YouTubeBundle\Component\Resource\VideoResource:
    tags: ['claroline.component.resource', 'kernel.event_subscriber']
    arguments:
      - '@security.token_storage'
      - '@Claroline\AppBundle\API\SerializerProvider'
      - '@Claroline\YouTubeBundle\Manager\EvaluationManager'
      - '@Claroline\YouTubeBundle\Manager\YouTubeManager'
