services:
    _defaults:
        tags: [ 'claroline.platform.updater' ]

    Mindme\MdhomeBundle\Installation\Updater\UpdaterMdhomeDefaults:
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'