services:
    Mindme\AibaseBundle\Component\Resource\AibaseResource:
        tags: ['claroline.component.resource']

    Mindme\AibaseBundle\Component\Resource\AiteacherResource:
        tags: ['claroline.component.resource']