services:
    Mindme\AibaseBundle\Serializer\AibaseSerializer:
        tags: ['claroline.serializer']
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Mindme\AibaseBundle\Library\SecretCipher'

    Mindme\AibaseBundle\Serializer\ResourceReferenceSerializer:
        tags: ['claroline.serializer']
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'