services:
    Mindme\AibaseBundle\Library\TTS\NullTTSProvider:
        tags:
            - { name: monolog.logger, channel: tts }

    Mindme\AibaseBundle\Library\TTS\EdgeTTSProvider:
        public: true