services:
    Claroline\MindMeAiBundle\Component\Resource\AiLessonResource:
        tags: ['claroline.component.resource']

    Claroline\MindMeAiBundle\Component\Resource\MindmeMarkdownResource:
        tags: ['claroline.component.resource']