services:
    Claroline\EvaluationBundle\Subscriber\ResourceEvaluationSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@messenger.default_bus'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\EvaluationBundle\Manager\ResourceEvaluationManager'

    Claroline\EvaluationBundle\Subscriber\SequenceEvaluationSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@Claroline\EvaluationBundle\Manager\SequenceEvaluationManager'

    Claroline\EvaluationBundle\Subscriber\WorkspaceEvaluationSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@messenger.default_bus'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\EvaluationBundle\Manager\WorkspaceEvaluationManager'
            - '@Claroline\EvaluationBundle\Manager\CertificateManager'

    Claroline\EvaluationBundle\Subscriber\Crud\SequenceSubscriber:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\CoreBundle\Manager\FileManager'

    # Data sources
    Claroline\EvaluationBundle\Subscriber\DataSource\ResourceAttemptSource:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\API\FinderProvider'

    Claroline\EvaluationBundle\Subscriber\DataSource\ResourceEvaluationSource:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\API\FinderProvider'

    Claroline\EvaluationBundle\Subscriber\DataSource\MyResourceEvaluationSource:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@Claroline\AppBundle\API\FinderProvider'

    Claroline\EvaluationBundle\Subscriber\DataSource\WorkspaceEvaluationSource:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\API\FinderProvider'

    Claroline\EvaluationBundle\Subscriber\DataSource\MyWorkspaceEvaluationSource:
        tags: [ 'kernel.event_subscriber' ]
        arguments:
            - '@security.token_storage'
            - '@Claroline\AppBundle\API\FinderProvider'
