services:
    Claroline\CoreBundle\Component\Context\WorkspaceContext:
        parent: Claroline\AppBundle\Component\Context\ContextComponent
        tags: [ 'claroline.component.context' ]
        arguments:
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\Manager\SecurityManager'
            - '@Claroline\CoreBundle\Manager\Workspace\WorkspaceManager'
            - '@Claroline\CoreBundle\Manager\Workspace\WorkspaceRestrictionsManager'

    Claroline\CoreBundle\Component\Context\PublicContext:
        parent: Claroline\AppBundle\Component\Context\ContextComponent
        tags: [ 'claroline.component.context' ]
        arguments:
            - '@Claroline\AppBundle\Manager\SecurityManager'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\Component\Context\DesktopContext:
        parent: Claroline\AppBundle\Component\Context\ContextComponent
        tags: [ 'claroline.component.context' ]
        arguments:
            - '@Claroline\AppBundle\Manager\SecurityManager'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\Component\Context\AdministrationContext:
        parent: Claroline\AppBundle\Component\Context\ContextComponent
        tags: [ 'claroline.component.context' ]
        arguments:
            - '@Claroline\AppBundle\Manager\SecurityManager'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
