# Declares all services required for the management of Claroline Components (e.g. resources).
services:
    # Resources
    Claroline\CoreBundle\Component\Resource\ResourceProvider:
        arguments:
            - !tagged_iterator claroline.component.resource
            - '@Claroline\AppBundle\Manager\File\TempFileManager'

    claroline.provider.resource:
        alias: Claroline\CoreBundle\Component\Resource\ResourceProvider
        public: true
