services:
    _defaults:
        tags: [claroline.validator]

    Claroline\CoreBundle\Validator\ResourceNodeValidator:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\Validator\PublicFileValidator:
        arguments:
            - '@Claroline\CoreBundle\Manager\FileManager'
