services:
    Claroline\PrivacyBundle\Component\Tool\PrivacyTool:
        parent: Claroline\AppBundle\Component\Tool\ToolComponent
        tags: [ 'claroline.component.tool' ]
        arguments:
            - '@Claroline\PrivacyBundle\Manager\PrivacyManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
