services:
    # Workspace
    Claroline\EvaluationBundle\Component\BadgeRule\Workspace\WorkspaceStatusRule:
        parent: Claroline\OpenBadgeBundle\Component\BadgeRule\RuleComponent
        tags: [ 'claroline.component.badge_rule' ]
        arguments:
            - '@translator'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\EvaluationBundle\Component\BadgeRule\Workspace\WorkspaceProgressionRule:
        parent: Claroline\OpenBadgeBundle\Component\BadgeRule\RuleComponent
        tags: [ 'claroline.component.badge_rule' ]
        arguments:
            - '@translator'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\EvaluationBundle\Component\BadgeRule\Workspace\WorkspaceScoreRule:
        parent: Claroline\OpenBadgeBundle\Component\BadgeRule\RuleComponent
        tags: [ 'claroline.component.badge_rule' ]
        arguments:
            - '@translator'
            - '@Claroline\AppBundle\Persistence\ObjectManager'


    # Resource
    Claroline\EvaluationBundle\Component\BadgeRule\Resource\ResourceStatusRule:
        parent: Claroline\OpenBadgeBundle\Component\BadgeRule\RuleComponent
        tags: [ 'claroline.component.badge_rule' ]
        arguments:
            - '@translator'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\EvaluationBundle\Component\BadgeRule\Resource\ResourceProgressionRule:
        parent: Claroline\OpenBadgeBundle\Component\BadgeRule\RuleComponent
        tags: [ 'claroline.component.badge_rule' ]
        arguments:
            - '@translator'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\EvaluationBundle\Component\BadgeRule\Resource\ResourceScoreRule:
        parent: Claroline\OpenBadgeBundle\Component\BadgeRule\RuleComponent
        tags: [ 'claroline.component.badge_rule' ]
        arguments:
            - '@translator'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
