services:
    Claroline\EvaluationBundle\Component\Template\EvaluationParticipationCertificatePdf:
        parent: Claroline\TemplateBundle\Component\Template\PdfComponent
        tags: [ 'claroline.component.template' ]

    Claroline\EvaluationBundle\Component\Template\EvaluationSuccessCertificatePdf:
        parent: Claroline\TemplateBundle\Component\Template\PdfComponent
        tags: [ 'claroline.component.template' ]
