plugin:
    tools:
        - name: import
          icon: file-import
          tool_rights:
              - import

        - name: export
          icon: file-export
          tool_rights:
              - export
