plugin:
    resources:
        - name: ai_lesson
          class: Claroline\MindMeAiBundle\Entity\AiLesson
        - name: mindme_markdown
          class: Claroline\MindMeAiBundle\Entity\MindmeMarkdown

    widgets:
        - name: landing-hero
          class: Claroline\MindMeAiBundle\Entity\Widget\LandingWidget
          context: [public]
          tags: [content]

        - name: landing-features
          class: Claroline\MindMeAiBundle\Entity\Widget\LandingWidget
          context: [public]
          tags: [content]

        - name: landing-packaging
          class: Claroline\MindMeAiBundle\Entity\Widget\LandingWidget
          context: [public]
          tags: [content]

        - name: dashboard-overview
          class: Claroline\MindMeAiBundle\Entity\Widget\LandingWidget
          context: [desktop]
          tags: [content]

        - name: dashboard-workspace-tree
          class: Claroline\MindMeAiBundle\Entity\Widget\LandingWidget
          context: [desktop]
          tags: [content]

        - name: dashboard-messages
          class: Claroline\MindMeAiBundle\Entity\Widget\LandingWidget
          context: [desktop]
          tags: [content]

        - name: dashboard-recommendations
          class: Claroline\MindMeAiBundle\Entity\Widget\LandingWidget
          context: [desktop]
          tags: [content]