services:
    Claroline\MindMeAiBundle\Controller\AiGeneratorController:
        tags: ['controller.service_arguments']
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@translator'
            - '@security.token_storage'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
    Claroline\MindMeAiBundle\Manager\DashboardStatsManager:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@security.token_storage'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@security.authorization_checker'
    Claroline\MindMeAiBundle\Serializer\AiLessonSerializer:
        tags: ['claroline.serializer']
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\MindMeAiBundle\Security\SecretCipher'
    Claroline\MindMeAiBundle\Serializer\DashboardWidgetSerializer:
        tags: ['claroline.serializer']
        arguments:
            - '@Claroline\MindMeAiBundle\Manager\DashboardStatsManager'
    Claroline\MindMeAiBundle\Serializer\ResourceReferenceSerializer:
        tags: ['claroline.serializer']
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'
    Claroline\MindMeAiBundle\Controller\ResourceReferenceController:
        tags: ['controller.service_arguments']
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\MindMeAiBundle\Serializer\ResourceReferenceSerializer'
            - '@security.authorization_checker'
            - '@security.token_storage'
    Claroline\MindMeAiBundle\Security\SecretCipher:
        arguments:
            - '%kernel.secret%'
    Claroline\MindMeAiBundle\Configuration\PlatformDefaults:
        tags: ['claroline.configuration']
