services:
    Claroline\SchedulerBundle\Command\ExecuteScheduledTasksCommand:
        arguments:
            - '@Claroline\SchedulerBundle\Manager\ScheduledTaskManager'
        tags:
            - { name: 'console.command', command: 'claroline:tasks:execute' }
