services:
    Mindme\MarkdownBundle\Serializer\MindmeMarkdownSerializer:
        tags: [claroline.serializer]

    Mindme\MarkdownBundle\Serializer\MarkdownWidgetSerializer:
        tags: [claroline.serializer]