services:
    Mindme\DigitalBundle\Component\Resource\DigitalTeacherResource:
        tags: ['claroline.component.resource']

    Mindme\DigitalBundle\Security\SecretCipher:
        arguments:
            - '%kernel.secret%'

    Mindme\DigitalBundle\Serializer\DigitalTeacherSerializer:
        tags: ['claroline.serializer']
        arguments:
            - '@Mindme\DigitalBundle\Security\SecretCipher'

    Mindme\DigitalBundle\TTS\NullTTSProvider:
        tags:
            - { name: monolog.logger, channel: tts }

    Mindme\DigitalBundle\TTS\EdgeTTSProvider:
        public: true

    Mindme\DigitalBundle\Controller\DigitalTeacherChatController:
        tags: ['controller.service_arguments']
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@security.authorization_checker'
            - '@Mindme\DigitalBundle\Security\SecretCipher'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Mindme\DigitalBundle\TTS\NullTTSProvider'
            - '@Mindme\DigitalBundle\TTS\EdgeTTSProvider'