services:
    Claroline\DevBundle\Listener\DebugToolbarListener:
        arguments:
            - '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }

    # Console Commands
    Claroline\DevBundle\Command\TranslationExportCommand:
        arguments:
            - '@kernel'
            - '@Claroline\CoreBundle\Manager\PluginManager'
            - '@Claroline\AppBundle\Manager\File\ArchiveManager'
        tags:
            - { name: 'console.command', command: 'claroline:translation:export' }
