services:
    Claroline\InstallationBundle\Command\PlatformInstallCommand:
        tags:
            - { name: 'console.command', command: 'claroline:install' }

    Claroline\InstallationBundle\Command\PlatformUpdateCommand:
        arguments:
            - '@Claroline\InstallationBundle\Manager\RefreshManager'
            - '@Claroline\InstallationBundle\Manager\PlatformManager'
            - '@Claroline\CoreBundle\Manager\VersionManager'
        tags:
            - { name: 'console.command', command: 'claroline:update' }

    Claroline\InstallationBundle\Command\Updater\ExecuteCommand:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - !tagged_locator
                  tag: 'claroline.platform.updater'
        tags:
            - { name: 'console.command', command: 'claroline:updater:execute' }

    # Migrations
    _instanceof:
        Claroline\InstallationBundle\Command\Migrations\AbstractCommand:
            calls:
                - [ setManager, [ '@claroline.migration.manager' ] ]

    Claroline\InstallationBundle\Command\Migrations\DowngradeCommand:
        tags:
            - { name: 'console.command', command: 'claroline:migration:downgrade' }

    Claroline\InstallationBundle\Command\Migrations\GenerateCommand:
        tags:
            - { name: 'console.command', command: 'claroline:migration:generate' }

    Claroline\InstallationBundle\Command\Migrations\UpgradeCommand:
        tags:
            - { name: 'console.command', command: 'claroline:migration:upgrade' }

    Claroline\InstallationBundle\Command\Migrations\VersionCommand:
        arguments:
            - '@claroline.migration.migrator'
        tags:
            - { name: 'console.command', command: 'claroline:migration:version' }
