services:
    claroline.migration.generator:
        class: Claroline\InstallationBundle\Migrations\Generator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@claroline.migration.doctrine_schema_tool'
    
    claroline.migration.writer:
        class: Claroline\InstallationBundle\Migrations\Writer
        arguments:
            - '@filesystem'
            - '@twig'
    
    claroline.migration.migrator:
        class: Claroline\InstallationBundle\Migrations\Migrator
        arguments:
            - '@doctrine.dbal.default_connection'
    
    claroline.migration.doctrine_schema_tool:
        class: Doctrine\ORM\Tools\SchemaTool
        arguments:
            - '@doctrine.orm.entity_manager'
