plugin:
    tools:
        - name: progression
          icon: route

    data_sources:
        - name: resource_attempts
          type: list
          context: [ workspace, desktop ]
          tags: [ activity, content ]

        - name: resource_evaluations
          type: list
          context: [ workspace, desktop ]
          tags: [ activity, content ]

        - name: my_resource_evaluations
          type: list
          context: [ workspace, desktop ]
          tags: [ activity ]

        - name: workspace_evaluations
          type: list
          context: [ workspace, desktop ]
          tags: [ content ]

        - name: my_workspace_evaluations
          type: list
          context: [ desktop ]
          tags: [ activity ]
